"""empty message

Revision ID: 94062dff0560
Revises: 9119741c33f2
Create Date: 2024-09-03 15:45:11.794442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94062dff0560'
down_revision = '9119741c33f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
